name: linux

on:
  - push
  - pull_request

jobs:
  perl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
          - '5.10-buster'
          - '5.12-buster'
          - '5.14-buster'
          - '5.16-buster'
          - '5.18-buster'
          - '5.20-buster'
          - '5.22-buster'
          - '5.24-buster'
          - '5.26'
          - '5.28'
          - '5.30'
          - '5.32'
          - '5.34'
          - '5.36'
    container:
      image: perl:${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v1
      - name: Install Net::SAML2 Depends
        run: |
          apt-get install libxml2 make gcc wget;
          mkdir -p $HOME/.cpanm ;
          cd $HOME/.cpanm;
          wget https://src.fedoraproject.org/repo/pkgs/perl-Math-Pari/pari-2.3.4.tar.gz/35c896266e4257793387ba22d5d76078/pari-2.3.4.tar.gz \
            -O pari-2.3.4.tar.gz ;
          echo '35c896266e4257793387ba22d5d76078  pari-2.3.4.tar.gz' | md5sum -c - ;
          tar zxf pari-2.3.4.tar.gz;
          cd - ;
          cpanm Math::Pari;
          cpanm --installdeps . ;
      - name: Build Module
        run: |
          perl Makefile.PL;
          make
      - name: Run Tests
        run: |
          prove -lr -l -b -I inc t
