---
name: linux

on:
  - push
  - pull_request

jobs:
  perl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
          - '5.12-buster'
          - '5.14-buster'
          - '5.16-buster'
          - '5.18-buster'
          - '5.20-buster'
          - '5.22-buster'
          - '5.24-buster'
          - '5.26'
          - '5.28'
          - '5.30'
          - '5.32'
          - '5.34'
          - '5.36'
        include:
          - perl-version: '5.38'
            release-test: true
            coverage: true
    container:
      image: perl:${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v1
      - name: Install Net::SAML2 Depends
        run: |
          apt-get install libxml2 make gcc wget;
          cpanm Module::Pluggable
          cpanm App::cpm;
          # Sub::Name has test that fail every so many times on t/lexical.t
          # we ignore these test failures for now...
          cpm install -g --show-build-log-on-failure Sub::Name;
          cpm install -g --test --show-build-log-on-failure --cpanfile cpanfile;
      - name: Build Module
        run: |
          perl Makefile.PL;
          make
      - name: Run tests
        if: ${{ !matrix.coverage  }}
        run: |
          prove -lr -l -b -I inc t
      - name: Run tests including coverage
        if: ${{ matrix.coverage  }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_PERL_SERVICE_NAME: github-actions
        run: |
          cpm install -g Devel::Cover::Report::Coveralls
          cover -test -report Coveralls
