---
name: perl-eol

on:
  workflow_run:
    workflows: ["perl-legacy"]
    types:
      - completed
    branches:
      - "**"

jobs:
  perl:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/shared-workflow.yml
    with:
      perl-version: ${{ matrix.perl-version }}
    strategy:
      matrix:
        perl-version:
          - '5.14-buster'
          - '5.16-buster'
          - '5.18-buster'
          - '5.20-buster'
          - '5.22-buster'
          - '5.24-buster'
